### ISSUE TITLE
Crashed when used with MaterialDrawer on device rotation

### ISSUE THREAD

**Issue by avgx** [palaima/DebugDrawer#18]
```
java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.widget.ScrollView$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/slider_layout. Make sure other views do not use the same id.
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3947)
            at android.app.ActivityThread.access$900(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.widget.ScrollView$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/slider_layout. Make sure other views do not use the same id.
            at android.view.View.onRestoreInstanceState(View.java:13764)
            at android.view.View.dispatchRestoreInstanceState(View.java:13740)
            at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2887)
            at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2893)
            at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2893)
            at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2893)
            at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2893)
            at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2893)
            at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2893)
            at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2893)
            at android.view.View.restoreHierarchyState(View.java:13718)
            at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2009)
            at android.app.Activity.onRestoreInstanceState(Activity.java:1023)
            at android.app.Activity.performRestoreInstanceState(Activity.java:978)
            at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1162)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3947)
            at android.app.ActivityThread.access$900(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```
it needs something like append in https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MultiDrawerActivity.java

**Comment by vanniktech** [comment]
I also had that problem. Both were using the same id, usually you can just rename the one from MaterialDrawer.
