### ISSUE TITLE
NetworkModule : SecurityException if no bluetooth permission on Android M

### ISSUE THREAD

**Issue by a-thomas** [palaima/DebugDrawer#62]
I got this exception:
```
Caused by: java.lang.SecurityException: Need BLUETOOTH permission: Neither user 10170 nor current process has android.permission.BLUETOOTH.
                                                                                                   at android.os.Parcel.readException(Parcel.java:1629)
                                                                                                   at android.os.Parcel.readException(Parcel.java:1582)
                                                                                                   at android.bluetooth.IBluetooth$Stub$Proxy.getState(IBluetooth.java:878)
                                                                                                   at android.bluetooth.BluetoothAdapter.getState(BluetoothAdapter.java:870)
                                                                                                   at io.palaima.debugdrawer.commons.NetworkController$NetworkReceiver.onReceive(NetworkController.java:217)
                                                                                                   at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:915)
                                                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                   at android.os.Looper.loop(Looper.java:168)
                                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5885)
                                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:819)
                                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:709)
```
It's due to a call to `bluetoothInfo.getState()` when no bluetooth permission is set in `NetworkController` at this [line](https://github.com/palaima/DebugDrawer/blob/90fa8fc25a6ba8d1e81e88969f3045d1943bc0d5/debugdrawer-commons/src/main/java/io/palaima/debugdrawer/commons/NetworkController.java#L217).

It's similar to #43.

**Comment by palaima** [comment]
Fix: fb0dfca9fca8f0a0e4b7287d0e1e37e5df6d0e38
